### ISSUE TITLE
Lack of information in false positive dashboard

### ISSUE THREAD

**Issue by zoriax** [f5devcentral/f5-waf-elk-dashboards#32]
Hi everyone,

First of all, thanks four your job ! It's really appreciable to have a good way to analyse false positive with NGINX and ELK. 

I tried your dash since a few days with NGINX and App Protect, it works nice but in my sense you have to add more informations in signature stats table, With only the singature ID, it's not esay to understand what is effetively blocked. With something like that it should be fine : 

![image](https://user-images.githubusercontent.com/12936546/104031207-bb26ea00-51cc-11eb-9c62-d08f80fa5ac6.png)

Actually there is a little problem with default log format, beacause more than one information is in sig_ids and sig_names, so Elastic add two entries in table. For exemple with the script "attack" test, you have as result :

![image](https://user-images.githubusercontent.com/12936546/104031644-46a07b00-51cd-11eb-9f2c-fda3c51dc051.png)

And I'm pretty sure it's not totally correct :-)

I'm not really a big user of ELK, so mybe it's certainly possible to do this but I dont know how.

Many thanks to consider this issue and if it could help you and have a solution it'll make me happy

Cheers !

**Comment by 464d41** [comment]
Hi @zoriax! Thanks for enhancement suggestion. Good point. I marked it accordingly.

Regarding duplicated data in the table. Does your logstash config splits sig_* fields by the comma signs? [Example link](https://github.com/464d41/f5-waf-elk-dashboards/blob/9fda8974a834b06b567900b0914b9651518cdc72/logstash/conf.d/30-waf-logs-full-logstash.conf#L51)

**Comment by zoriax** [comment]
Hi @464d41,

Sorry for my very very later answer, I was busy on others projects :-). So to confirm yes is user the split. Do you have a solution or some good new since my previous post ?
