### ISSUE TITLE
unable to deploy elk

### ISSUE THREAD

**Issue by f5killer** [f5devcentral/f5-waf-elk-dashboards#39]
unable to deploy elk.

root@ip-172-31-82-81:/home/ubuntu# docker logs 74b86268788f
 * Starting periodic command scheduler cron
   ...done.
 * Starting Elasticsearch Server
future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-8-openjdk-amd64/jre] does not meet this requirement
   ...done.

**Comment by aknot242** [comment]
This is a warning and can be ignored. 

What are the steps used to install ELK? What resources does the container host have (CPU, memory, disk)?

**Comment by f5killer** [comment]
unable to install due to java eror error. Suspecting some script needs to modify in docker-compose. 
CPU: 2Core
Memory: 4GB RAM
Disk: 40GB

**Comment by aknot242** [comment]
I just tested on Ubuntu 20.04 using your system specs and it works fine for me. Keep in mind the Java message is just a warning that can be ignored with this version. If you are seeing startup errors, you may have skipped this step: 

https://www.elastic.co/guide/en/elasticsearch/reference/5.0/vm-max-map-count.html#vm-max-map-count

Here's my log output:

```
ubuntu@ip-10-1-11-32:~/f5-waf-elk-dashboards$ docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS         PORTS                                                                                                                                                 NAMES
ef1d6a7a12c2   sebp/elk:742   "/usr/local/bin/star…"   7 minutes ago   Up 7 minutes   0.0.0.0:5144->5144/tcp, :::5144->5144/tcp, 0.0.0.0:5601->5601/tcp, :::5601->5601/tcp, 5044/tcp, 9300/tcp, 0.0.0.0:9200->9200/tcp, :::9200->9200/tcp   f5-waf-elk-dashboards_elasticsearch_1

ubuntu@ip-10-1-11-32:~/f5-waf-elk-dashboards$ docker logs ef
 * Starting periodic command scheduler cron
   ...done.
 * Starting Elasticsearch Server
future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-8-openjdk-amd64/jre] does not meet this requirement
   ...done.
waiting for Elasticsearch to be up (1/30)
waiting for Elasticsearch to be up (2/30)
waiting for Elasticsearch to be up (3/30)
waiting for Elasticsearch to be up (4/30)
waiting for Elasticsearch to be up (5/30)
waiting for Elasticsearch to be up (6/30)
waiting for Elasticsearch to be up (7/30)
waiting for Elasticsearch to be up (8/30)
waiting for Elasticsearch to be up (9/30)
waiting for Elasticsearch to be up (10/30)
waiting for Elasticsearch to be up (11/30)
waiting for Elasticsearch to be up (12/30)
waiting for Elasticsearch to be up (13/30)
Waiting for Elasticsearch cluster to respond (1/30)
logstash started.
 * Starting Kibana5
   ...done.

**Comment by f5killer** [comment]
issue solved

**Comment by deywang** [comment]
how to solved
