### ISSUE TITLE
Installation instructions not so clear...

### ISSUE THREAD

**Issue by vicki-nginx** [f5devcentral/f5-waf-elk-dashboards#9]
In trying to setup ELK on my NGINX Net App system, I thought from reading the following that I had to already have elasticsearch setup before using the docker stuff...
It is assumed you have ELK stack up and running.

**Comment by 464d41** [comment]
Do you have any suggestions on how to improve README?

**Comment by aknot242** [comment]
@vicki-nginx I contributed PR #9 in case that helps.
